Repository Student-Center/weave-server, pull requests merged in 2024-02, with the labels that each got.

#42 [WEAV-128] 회원 정보 조회 모의 응답 구성
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/UserGetMyProfileResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/config/OpenApiConfig.kt
Labels: feat

#45 [WEAV-128] 회원 정보 모의응답 타입 수정
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/UserGetMyProfileResponse.kt
Labels: fix

#46 [WEAV-137] 인증 필터, 인가 인터셉터 구현
  application/src/main/kotlin/com/studentcenter/weave/application/common/security/context/UserSecurityContext.kt
  application/src/main/kotlin/com/studentcenter/weave/application/common/security/vo/UserAuthentication.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/vo/UserTokenClaimsFixtureFactory.kt
  bootstrap/http/build.gradle.kts
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/config/WebMvcConfig.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/ApiExceptionType.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/annotation/Secured.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/filter/JwtAuthenticationFilter.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/interceptor/AuthorizationInterceptor.kt
  bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/common/security/filter/JwtAuthenticationFilterTest.kt
  bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/common/security/interceptor/AuthorizationInterceptorTest.kt
  bootstrap/http/src/testFixtures/kotlin/com/studentcenter/weave/bootstrap/controller/AuthorizationInterceptorTestController.kt
  bootstrap/http/src/testFixtures/kotlin/com/studentcenter/weave/bootstrap/controller/JwtAuthenticationFilterTestController.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/authority/Authentication.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/context/SecurityContext.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/context/SecurityContextHolder.kt
Labels: feat

#47 [WEAV-137] Secured 어노테이션 적용 (로그아웃, 사용자 프로필 API)
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/annotation/Secured.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/interceptor/AuthorizationInterceptor.kt
Labels: feat

#52 [WEAV-152] 미팅 팀 도메인 구현
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeam.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/enums/Location.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/vo/TeamIntroduce.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeamTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/meeting/vo/TeamIntroduceTest.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/entity/MeetingTeamJpaEntity.kt
  infrastructure/persistence/src/main/resources/db/migration/V5__create_meeting_team.sql
Labels: feat

#53 [WEAV-164] 외부 인프라 레이어 value class 사용하지 않도록 수정
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/CustomExceptionHandler.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/controller/UnivRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/dto/MajorsResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/dto/UniversitiesResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/dto/UniversityResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetMyProfileResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserRegisterRequest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/BirthYear.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Height.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/entity/MajorJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/entity/UniversityJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/DeletedUserInfoJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserAuthInfoJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserJpaEntity.kt
Labels: fix

#54 [WEAV-161] 회원 탈퇴 유스케이스 구현
  application/src/main/kotlin/com/studentcenter/weave/application/common/security/context/UserSecuritySupport.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserUnregisterUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserAuthInfoRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserUnregisterApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/DeletedUserInfoService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserAuthInfoDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/DeletedUserInfoServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserAuthInfoDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserUnregisterApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/DeletedUserInfoRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserAuthInfoRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserAuthInfoJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/repository/UserAuthInfoJpaRepository.kt
  infrastructure/persistence/src/main/resources/db/migration/V6__create_deleted_user_info.sql
Labels: feat

#55 [WEAV-129] 유저 정보 조회 유스케이스 구현
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetMyProfileUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationServiceTest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
Labels: feat

#56 [WEAV-169] 회원 키설정 API 구현
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserSetMyHeightUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyHeightApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyHeightApplicationServiceTest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserSetMyHeightRequest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/vo/UpdateParam.kt
Labels: feat

#57 [WEAV-170] 회원 닮은 동물상 등록 유스케이스 구현
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserSetMyAnimalTypeUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyAnimalTypeApplicationService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyAnimalTypeApplicationServiceTest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserSetMyAnimalTypeRequest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/enums/AnimalType.kt
Labels: feat

#58 [WEAV-171] Mbti 수정 API 구현
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserModifyMyMbtiUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserModifyMyMbtiApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserModifyMyMbtiApplicationServiceTest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserModifyMyMbtiRequest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
Labels: feat

#59 [WEAV-175] 미팅 팀 생성 API 구현
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamCreateUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingTeamRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingTeamRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamCreateRequest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeam.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/enums/MeetingTeamStatus.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeamTest.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingTeamJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/entity/MeetingTeamJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingTeamJpaRepository.kt
  infrastructure/persistence/src/main/resources/db/migration/V7__meeting_team_add_status_column.sql
Labels: feat

#60 [WEAV-177] 유저 실 도메인 정의
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserSil.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/user/entity/UserSilTest.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserSilJpaEntity.kt
  infrastructure/persistence/src/main/resources/db/migration/V8__create_user_sil.sql
Labels: feat

#61 [WEAV-178] 실 관련 기능 추가
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetMyProfileUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserSilRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyAnimalTypeApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyHeightApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserSilDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserSilDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyAnimalTypeApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyHeightApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserSilRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetMyProfileResponse.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserSil.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/user/entity/UserFixtureFactory.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserSilJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserSilJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/repository/UserSilJpaRepository.kt
  infrastructure/persistence/src/main/resources/db/migration/V9__change_user_id_index_to_unique.sql
Labels: feat

#66 [WEAV-129] 유저 본인 정보 조회 API 응답, 대학 이름 누락 추가
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetMyProfileUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationService.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetMyProfileResponse.kt
Labels: feat

#67 [WEAV-176] 미팅팀 Gender 컬럼 추가
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationServiceTest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyResponse.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeam.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeamTest.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/entity/MeetingTeamJpaEntity.kt
  infrastructure/persistence/src/main/resources/db/migration/V11__change_meeting_team_add_gender.sql
Labels: feat

#68 [WEAV-185] university and major implement
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/MajorFindAllByUniversityApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/UniversityFindAllApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByIdApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/domain/impl/MajorDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/domain/impl/UniversityDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/MajorFindAllByUnversityUsecase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UniversityFindAllUsecase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UniversityGetByIdUsecase.kt
  application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/MajorFindAllByUniversityApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/UniversityFindAllApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByIdApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/university/port/outbound/MajorRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/university/port/outbound/UniversityRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/controller/UnivRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/dto/UniversitiesResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/dto/UniversityResponse.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/university/entity/University.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/university/entity/MajorFixtureFactory.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/university/entity/UniversityFixtureFactory.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/adapter/MajorJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/adapter/UniversityJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/entity/MajorJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/entity/UniversityJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/repository/MajorJpaRepository.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/repository/UniversityJpaRepository.kt
Labels: feat

#70 [WEAV-187] 내 미팅팀 조회 응답 API 모의 응답 구현
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamGetMyUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamGetMyApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/vo/MeetingTeamInfo.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyResponse.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollRequest.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollResponse.kt
Labels: feat

#72 [WEAV-187] 내 미팅팀 조회 모의응답 API 요청 & 응답 수정
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamGetMyUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamGetMyApplicationService.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyRequest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyResponse.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollRequest.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollResponse.kt
Labels: fix

#71 [WEAV-186] mailer 정의 및 gmail adaptor implement
  .github/workflows/develop_server_integrator.yaml
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/VerificationNumberMailer.kt
  bootstrap/http/compose-dev.yaml
  buildSrc/src/main/kotlin/Version.kt
  infrastructure/mail/build.gradle.kts
  infrastructure/mail/src/main/kotlin/com/studentcenter/weave/infrastructure/mail/adaptor/VerificationNumberGmailAdaptor.kt
  infrastructure/mail/src/main/kotlin/com/studentcenter/weave/infrastructure/mail/common/config/MailConfig.kt
  infrastructure/mail/src/main/kotlin/com/studentcenter/weave/infrastructure/mail/common/exception/MailExceptionType.kt
  infrastructure/mail/src/main/kotlin/com/studentcenter/weave/infrastructure/mail/ses/config/SesConfig.kt
  infrastructure/mail/src/main/kotlin/com/studentcenter/weave/infrastructure/mail/ses/properties/SesProperties.kt
  infrastructure/mail/src/main/kotlin/com/studentcenter/weave/infrastructure/mail/ses/service/AmazonSimpleEmailService.kt
  infrastructure/mail/src/main/resources/application-mail.yaml
  infrastructure/mail/src/main/resources/mail-templates/email-verification-number.html
  settings.gradle.kts
  support/mail/build.gradle.kts
Labels: feat

#73 [WEAV-190] 유저 학교 인증 도메인 및 persistence 작업
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserUniveristyVerificationInfo.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserUniveristyVerificationInfoJpaEntity.kt
  infrastructure/persistence/src/main/resources/db/migration/V12__create_user_university_verification_info.sql
Labels: feat

#74 [WEAV-191] 학교 이메일 인증 작업 및 테스트 작성
  application/src/main/kotlin/com/studentcenter/weave/application/common/exception/UniversityVerificationExceptionType.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserSendVerificationNumberEmailUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserVerifyVerificationNumberUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserUniversityVerificationInfoRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserVerificationNumberRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/VerificationNumberMailer.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserSendVerificationNumberEmailApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserVerifyVerificationNumberApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserSilDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserUniversityVerificationInfoDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserSilDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserUniversityVerificationInfoDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/vo/UserUniversityVerificationNumber.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSendVerificationNumberEmailApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserVerifyVerificationNumberApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserUniversityVerificationInfoRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserVerificationNumberRepositorySpy.kt
  bootstrap/http/build.gradle.kts
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserUnivVerificationSendRequest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserUnivVerificationVerifyRequest.kt
  bootstrap/http/src/main/resources/application.yaml
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserUniversityVerificationInfo.kt
  infrastructure/mail/src/main/kotlin/com/studentcenter/weave/infrastructure/mail/adaptor/VerificationNumberGmailAdaptor.kt
  infrastructure/mail/src/main/kotlin/com/studentcenter/weave/infrastructure/mail/common/config/MailConfig.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserUniversityVerificationInfoJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserUniveristyVerificationInfoJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/repository/UserUniversityVerificationInfoJpaRepository.kt
  infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/user/adapter/UserVerificationNumberRedisAdapter.kt
  infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/user/entity/UserVerificationNumberRedisHash.kt
  infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/user/repository/UserVerificationNumberRedisRepository.kt
Labels: feat

#79 [WEAV-196] 개발 DB 해킹으로 인한 패스워드 환경변수화
  bootstrap/http/compose-dev.yaml
  infrastructure/persistence/src/main/resources/application-persistence.yaml
Labels: feat

#80 [WEAV-196] 서버 계정 이관
  .github/workflows/develop_server_integrator.yaml
Labels: fix

#81 [WEAV-196] 서버 계정 이관
  bootstrap/http/compose-dev.yaml
Labels: fix

#86 [WEAV-176] 미팅팀 생성 유스케이스 리팩터링
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingMemberRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingTeamRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamGetMyApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserQueryUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserQueryApplicationService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImplTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingMemberRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingTeamRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/inbound/UserQueryUseCaseStub.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingMember.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeam.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/enums/MeetingMemberRole.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeamTest.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeamFixtureFactory.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/user/entity/UserFixtureFactory.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingMemberJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingTeamJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/entity/MeetingMemberJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/entity/MeetingTeamJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingMemberJpaRepository.kt
  infrastructure/persistence/src/main/resources/db/migration/V13__create_meeting_member.sql
Labels: refactor

#91 [WEAV-176] 내 미팅팀 조회 유스케이스 구현
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamGetMyUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingMemberRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingTeamRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamGetMyApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/vo/MeetingTeamInfo.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingMemberRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingTeamRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyRequest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserRegisterRequest.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingMemberJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingTeamJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingMemberJpaRepository.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingTeamJpaRepository.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollResponse.kt
Labels: feat

#94 [WEAV-203] 미팅팀 수정 유스케이스 구현
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamEditUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamEditApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamEditApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingMemberRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamEditRequest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeam.kt
Labels: feat

#96 [WEAV-217] 미팅팀 목록 상세 기능 API 모의 응답 구현
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetDetailResponse.kt
Labels: feat

#101 [WEAV-218] 미팅 팀 상세조회 유스케이스 구현
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamGetDetailUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetMyApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MeetingMemberDetailInfo.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/port/inbound/MajorGetByIdUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/port/inbound/UniversityGetByIdUsecase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/MajorGetByIdApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByIdApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetByIdUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetByIdApplicationService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByIdApplicationServiceTest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetDetailResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/controller/UnivRestController.kt
Labels: feat

#109 [WEAV-236] 대표 MBTI 계산 로직 작성
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Mbti.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/MbtiTest.kt
Labels: feat

#110 [WEAV-227] 미팅팀 나가기 API 구현
  application/src/main/kotlin/com/studentcenter/weave/application/common/exception/MeetingTeamExceptionType.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamLeaveUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingMemberRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingMemberRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/api/MeetingTeamApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingMemberJpaAdapter.kt
Labels: feat

#114 [WEAV-234] 미팅팀 공개 로직 구현
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamMemberSummaryRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamDeleteApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamEditApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImplTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamMemberSummaryRepositorySpy.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeam.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeamMemberSummary.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingTeamMemberSummaryJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamMemberSummaryJpaRepository.kt
Labels: feat

#115 [WEAV-231] flyway 버전 이슈 수정
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingTeamMemberSummaryJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamMemberSummaryJpaRepository.kt
  infrastructure/persistence/src/main/resources/db/migration/V15__create_meeting_team_member_summary.sql
Labels: fix

#118 [WEAV-153] 미팅팀 목록조회 API
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamGetListUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetListApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MeetingTeamListFilter.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/api/MeetingTeamApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetListRequest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/enums/Gender.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingTeamJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamJpaRepository.kt
Labels: feat

#122 [WEAV-250] 미팅 요청 API 구현
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingRequestUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamQueryUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamQueryApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserQueryUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserQueryApplicationService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/inbound/UserQueryUseCaseStub.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingRequestRequest.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingMemberFixtureFactory.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingAttendanceJpaRepository.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingTeamJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamJpaRepository.kt
Labels: feat

#125 [WEAV-000] 테스트 실패 버그 해결
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetDetailApplicationServiceTest.kt
Labels: hotfix

#127 [WEAV-246] 팀 상세조회 응답 테스트 수정
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetDetailApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamRepositorySpy.kt
Labels: feat, fix

#132 [WEAV-203] 팀 공개시 수정 불가
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamEditApplicationService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamEditApplicationServiceTest.kt
Labels: fix

#126 [WEAV-256] Trailing Lambdas활용 분산락 AOP 구현
  application/build.gradle.kts
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserSilDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyAnimalTypeApplicationServiceTest.kt
  bootstrap/http/build.gradle.kts
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
  bootstrap/http/src/main/resources/application.yaml
  bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/integration/IntegrationTestDescribeSpec.kt
  bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/integration/UserSilDomainServiceIntegrationTest.kt
  bootstrap/http/src/test/resources/compose-test.yaml
  build.gradle.kts
  buildSrc/src/main/kotlin/Version.kt
  infrastructure/persistence/build.gradle.kts
  infrastructure/persistence/src/main/resources/application-persistence.yaml
  infrastructure/redis/src/main/resources/application-redis.yaml
  support/lock/build.gradle.kts
  support/lock/src/main/kotlin/com/studentcenter/weave/support/lock/DistributedLock.kt
  support/lock/src/main/kotlin/com/studentcenter/weave/support/lock/DistributedLockAspect.kt
  support/lock/src/main/kotlin/com/studentcenter/weave/support/lock/DistributedLockConfig.kt
  support/lock/src/main/kotlin/com/studentcenter/weave/support/lock/DistributedLockTransactionProcessor.kt
Labels: feat

#133 [WEAV-153] 미팅팀 목록 조회 다수 Location 쿼리 버그 수정
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingTeamJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamJpaRepository.kt
Labels: fix

#134 [WEAV-259] 미팅 참여 / 패스 로직 처리
  application/src/main/kotlin/com/studentcenter/weave/application/common/exception/MeetingExceptionType.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingAttendanceCreateUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingAttendanceRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingAttendanceCreateApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingAttendanceDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingAttendanceDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamMemberQueryUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingMemberRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamMemberQueryApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamMemberDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamMemeberDomainServiceImpl.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingAttendanceRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingMemberRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingAttendanceCreateRequest.kt
  bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/integration/MeetingAttendanceCreateApplicationServiceIntegrationTest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/Meeting.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingAttendanceJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingAttendanceJpaRepository.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingMemberJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingMemberJpaRepository.kt
Labels: feat

#137 [WEAV-262] 카카오톡 ID등록 API 구현
  application/build.gradle.kts
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetMyProfileUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserSetMyKakaoIdUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyKakaoIdApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyKakaoIdApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetMyProfileResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserSetMyKakaoIdRequest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/KakaoId.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/user/entity/UserFixtureFactory.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/repository/UserJpaRepository.kt
  infrastructure/persistence/src/main/resources/db/migration/V16__add_user_kakao_id.sql
  support/lock/build.gradle.kts
  support/lock/src/testFixtures/kotlin/com/studentcetner/weave/support/lock/DistributedLockTestInitializer.kt
Labels: feat

#139 [WEAV-265] 해당 team에 대한 요청 조회
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/FindMyRequestMeetingByReceivingTeamIdUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/FindMyRequestMeetingByReceivingTeamIdApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/FindMyRequestMeetingByReceivingTeamIdApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingResponse.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingJpaRepository.kt
Labels: feat

#144 [WEAV-000] Add univ verified in member detail
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MeetingMemberDetailInfo.kt
Labels: fix

#145 [WEAV-000] 유저 이메일 확인 여부 응답 추가
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetDetailResponse.kt
Labels: hotfix
