Repository Student-Center/weave-server, pull requests merged in 2024-03, with the labels that each got.

#164 [WEAV-266] 회원 프로필 이미지 업로드 Presigned URL 조회 구현
  .github/workflows/unit_test_runner.yaml
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetProfileImageUploadUrlUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPort.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetProfileImageUploadUrlApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/vo/ImageFileExtension.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserGetProfileImageUploadUrlApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPortStub.kt
  bootstrap/http/build.gradle.kts
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/auth/dto/DomainResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetProfileImageUploadUrlResponse.kt
  bootstrap/http/src/main/resources/application.yaml
  buildSrc/src/main/kotlin/Version.kt
  infrastructure/aws/build.gradle.kts
  infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/config/AwsConfig.kt
  infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/s3/adapter/UserProfileImageUrlS3Adapter.kt
  infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/s3/config/S3BucketProperties.kt
  infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/s3/config/S3Config.kt
  infrastructure/aws/src/main/resources/application-aws.yaml
  settings.gradle.kts
Labels: feat

#165 [WEAV-266] 유저 프로필 이미지 업로드 콜백 구현
  application/src/main/kotlin/com/studentcenter/weave/application/common/exception/UserExceptionType.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserCompleteProfileImageUploadUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPort.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserCompleteProfileImageUploadApplicationService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserCompleteProfileImageUploadApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPortStub.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
  infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/s3/adapter/UserProfileImageUrlS3Adapter.kt
  infrastructure/aws/src/main/resources/application-aws.yaml
Labels: feat

#172 [WEAV-000] Fix scroll meeting team
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetListApplicationService.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamRepositorySpy.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamJpaRepository.kt
Labels: fix

#176 [WEAV-293] 🚀 HeadVer 버전 시스템 태그 생성 수정 및 GitHub 릴리스 자동화
  .github/workflows/develop_server_integrator.yaml
Labels: feat, fix

#177 [WEAV-293] 🐛 workflow 버전 인자 수정
  .github/workflows/develop_server_integrator.yaml
Labels: fix

#179 [WEAV-294] 👷 CD시 배포로 수정
  .github/workflows/develop_server_deployer.yaml
  .github/workflows/develop_server_integrator.yaml
  bootstrap/http/compose-dev.yaml
Labels: feat

#181 [WEAV-000] 토큰 만료시간 수정
  .github/workflows/develop_server_deployer.yaml
  application/src/main/resources/application-application.yaml
Labels: fix

#184 [WEAV-000] 정적 리소스 요청 stacktrace 로그 제거
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/UnknownExceptionHandler.kt
  infrastructure/persistence/src/main/resources/application-persistence.yaml
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/exception/SystemExceptionType.kt
Labels: fix

#187 [WEAV-000] 버전 pull 관련 이슈 해결
  .github/workflows/develop_server_integrator.yaml
  bootstrap/http/compose-dev.yaml
Labels: fix

#191 [WEAV-295] 서버 환경변수 정리
  .github/workflows/develop_server_deployer.yaml
  application/src/main/resources/application-application.yaml
  bootstrap/http/compose-dev.yaml
  bootstrap/http/src/main/resources/application.yaml
  infrastructure/persistence/src/main/resources/application-persistence.yaml
  infrastructure/redis/src/main/resources/application-redis.yaml
Labels: refactor

#193 [WEAV-295] cd workflow env파일 생성 오류 수정
  .github/workflows/develop_server_deployer.yaml
Labels: fix

#202 [WEAV-000] 타임존 설정
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
Labels: fix

#204 [WEAV-000] Change cron schedule
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/scheduler/component/PendingMeetingExpireScheduler.kt
Labels: feat

#207 [WEAV-000] PendingMeeting제거 쿼리 transaction 추가
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/CancelEndedPendingMeetingApplicationService.kt
Labels: fix

#210 [WEAV-000] Fix my team scroll next 처리
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetMyApplicationService.kt
Labels: fix

#211 [WEAV-00] Fix prepared team location name -> value
  .github/workflows/pr_validator.yml
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/PreparedMeetingScrollResponse.kt
Labels: fix

#212 [WEAV-266] 프로필 이미지 업로드 API 스펙 변경
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserCompleteProfileImageUploadUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetProfileImageUploadUrlUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPort.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserCompleteProfileImageUploadApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetProfileImageUploadUrlApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/vo/ImageFileExtension.kt
  application/src/main/resources/application-application.yaml
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserCompleteProfileImageUploadApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserGetProfileImageUploadUrlApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserVerifyVerificationNumberApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImplTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPortStub.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserCompleteProfileImageUploadRequest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetProfileImageUploadUrlResponse.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserProfileImage.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/user/entity/UserTest.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/user/entity/UserFixtureFactory.kt
  infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/s3/adapter/UserProfileImageUrlS3Adapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserProfileImageJpaEntity.kt
  infrastructure/persistence/src/main/resources/db/migration/V18__add_profile_image.sql
Labels: fix

#215 [WEAV-266] 프로필 이미지 URL 조회 실패 예외케이스 처리
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserProfileImage.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/exception/UserExceptionType.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/user/entity/UserProfileImageTest.kt
Labels: feat, fix

#216 [WEAV-311] 동물상 전체 조회 API 구현
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetAvailableAnimalTypesResponse.kt
Labels: feat

#217 [WEAV-311] animalType 유저 친화 응답으로 변경
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/PreparedMeetingScrollResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetDetailResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetMyProfileResponse.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/user/enums/AnimalType.kt
Labels: fix

#206 [WEAV-278] 디스코드 이벤트 WEB HOOK 구현
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingEventPort.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingAttendanceCreateApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/vo/MeetingMatchingEvent.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamQueryUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamQueryApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserRegisterUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserEventPort.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserEventPortStub.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Version.kt
  infrastructure/client/build.gradle.kts
  infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/common/config/ClientConfig.kt
  infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/common/event/EventType.kt
  infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/common/properties/ClientProperties.kt
  infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/common/vo/DiscordMessage.kt
  infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/meeting/adaptor/MeetingEventDiscordAdaptor.kt
  infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/user/adaptor/UserEventDiscordAdaptor.kt
  infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/util/DiscordClient.kt
  infrastructure/client/src/main/resources/application-client.yaml
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/common/exception/PersistenceException.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingJpaRepository.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/repository/UserJpaRepository.kt
Labels: feat

#218 [WEAV-000] Version Catalog 방식으로 버전 관리 변경
  application/build.gradle.kts
  bootstrap/http/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Version.kt
  gradle/libs.versions.toml
  infrastructure/aws/build.gradle.kts
  infrastructure/client/build.gradle.kts
  infrastructure/mail/build.gradle.kts
  infrastructure/persistence/build.gradle.kts
  infrastructure/redis/build.gradle.kts
  support/common/build.gradle.kts
  support/lock/build.gradle.kts
  support/security/build.gradle.kts
Labels: hotfix

#220 [WEAV-000] isUserUniversityVerified 메서드 제거, User객체로 직접 확인하는 방식으로 변경
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/GetUser.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/GetUserService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/inbound/GetUserStub.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/user/entity/UserFixtureFactory.kt
Labels: refactor

#222 [WEAV-000] University, Major UseCase 리펙터링
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/GetAllOtherTeamMemberInfoApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetDetailApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetListApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetMyApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamInfoGetAllByIdApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/port/inbound/GetMajor.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/port/inbound/GetUniversity.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/port/inbound/MajorFindAllByUniversityUsecase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/port/inbound/UniversityFindAllUsecase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/port/inbound/UniversityGetByIdUsecase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/GetMajorService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/GetUniversityService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/MajorFindAllByUniversityApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/UniversityFindAllApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByIdApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByNameApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/domain/MajorDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/university/service/domain/impl/MajorDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/GetAllOtherTeamMemberInfoApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetDetailApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/GetMajorTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/GetUniversityTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/UniversityFindAllApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByIdApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByNameApplicationServiceTest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/controller/UnivRestController.kt
Labels: refactor

#221 [WEAV-316] 여러 개의 미팅 팀 참여 방지
  application/src/main/kotlin/com/studentcenter/weave/application/common/exception/MeetingTeamExceptionType.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingMemberRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImplTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingMemberRepositorySpy.kt
  bootstrap/http/build.gradle.kts
  bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/integration/MeetingAttendanceCreateApplicationServiceIntegrationTest.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingMemberJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingMemberJpaRepository.kt
Labels: fix

#225 [WEAV-000] 미팅팀 멤버 조회 메서드 리펙터링
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/GetAllOtherTeamMemberInfoApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingAttendanceCreateApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/GetMeetingTeam.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/GetMeetingTeamMembers.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingMemberRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/GetMeetingTeamMemberQueryApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/GetMeetingTeamService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamMemberDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamMemeberDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/GetAllOtherTeamMemberInfoApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingMemberRepositorySpy.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingMemberJpaAdapter.kt
Labels: refactor
