Repository Student-Center/weave-server, pull requests merged in 2024-01, with the labels that each got.

#2 [WEAV-15] JIRA 티켓 연동 및 githook. 구성
  .githooks/install.sh
  .githooks/prepare-commit-msg
  .github/codeowners
  README.md
Labels: config

#4 [WEAV-30] Add PR title validation workflow
  .github/workflows/pr-title-validation.yml
Labels: config

#5 [WEAV-19] 프로젝트 구조 설정
  application/build.gradle.kts
  bootstrap/http/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Version.kt
  domain/build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  infrastructure/client/build.gradle.kts
  infrastructure/persistence/build.gradle.kts
  settings.gradle.kts
  support/common/build.gradle.kts
  support/lock/build.gradle.kts
  support/logger/build.gradle.kts
  support/mail/build.gradle.kts
Labels: config

#3 [WEAV-16] 🔧 SonarCloud 관련 설정
  .github/workflows/sonar_cloud.yaml
  bootstrap/http/build.gradle.kts
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Version.kt
Labels: config

#7 [WEAV-31] ✨ UUID Creator Util 설정
  buildSrc/src/main/kotlin/Version.kt
  support/common/build.gradle.kts
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/uuid/UuidCreator.kt
Labels: feat

#8 [WEAV-20] ✨ 소셜 로그인 API 모의 응답 구현
  bootstrap/http/build.gradle.kts
  bootstrap/http/compose-dev.yaml
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/AuthRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RefreshLoginTokenResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/SocialLoginResponse.kt
  bootstrap/http/src/main/resources/application.yaml
  buildSrc/src/main/kotlin/Version.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/enum/SocialLoginProvider.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/vo/Email.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/vo/Url.kt
  support/common/src/test/kotlin/com/studentcenter/weave/support/common/vo/EmailTest.kt
  support/common/src/test/kotlin/com/studentcenter/weave/support/common/vo/UrlTest.kt
Labels: feat

#10 [WEAV-44] 👷 CD 프로세스 구현
  .github/workflows/cd_dev.yaml
  .github/workflows/ci_dev.yaml
  bootstrap/http/compose-dev.yaml
Labels: config

#11 [WEAV-45] 테스트 서버 compose 포트 수정
  bootstrap/http/compose-dev.yaml
Labels: config

#12 [WEAV-46] Open API3 영어로 변경
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RefreshLoginTokenResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/SocialLoginResponse.kt
Labels: fix

#13 [WEAV-50] 개발서버내 docker cache로 인한 CD 반영 안됨 이슈 해결
  bootstrap/http/compose-dev.yaml
Labels: fix

#14 [WEAV-46] 회원가입 API 구현
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/UserApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RegisterUserRequest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RegisterUserResponse.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/enum/Gender.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/enum/Mbti.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/BirthYear.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/Department.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/University.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/vo/BirthYearTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/vo/DepartmentTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/vo/UniversityTest.kt
Labels: feat

#15 [WEAV-50] 개발 서버 배포 이슈 해결
  .github/workflows/cd_dev.yaml
Labels: fix

#16 [WEAV-51] 유저, 유저 인증정보, 유저 탈퇴정보 도메인 구현
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RegisterUserRequest.kt
  domain/build.gradle.kts
  domain/src/main/kotlin/com/studentcenter/weave/domain/entity/DeactivateUserInfo.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/entity/User.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/entity/UserAuthInfo.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/Department.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/Major.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/Nickname.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/entity/DeactivateUserInfoTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/entity/UserAuthInfoTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/entity/UserTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/vo/DepartmentTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/vo/MajorTest.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/entity/DeactivateUserInfoFixtureFactory.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/entity/UserAuthInfoFixtureFactory.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/entity/UserFixtureFactory.kt
Labels: feat

#18 [WEAV-63] 로그인 API 파라미터명 수정
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/AuthRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RefreshTokenRequest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/SocialLoginRequest.kt
Labels: fix

#19 [WEAV-49] 로그인 기능 애플리케이션 레이어 구현
  application/build.gradle.kts
  application/src/main/kotlin/com/studentcenter/weave/application/common/config/ApplicationConfig.kt
  application/src/main/kotlin/com/studentcenter/weave/application/port/inbound/UserSocialLoginUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/UserTokenService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/application/UserSocialLoginApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/domain/UserAuthInfoDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/domain/UserDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/vo/UserTokenClaims.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserSocialLoginApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/UserTokenServiceStub.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/domain/UserDomainServiceStub.kt
Labels: feat

#21 [WEAV-64] 로그인 기능 토큰 발급 지원모듈 개발
  application/src/main/kotlin/com/studentcenter/weave/application/common/properties/JwtTokenProperties.kt
  buildSrc/src/main/kotlin/Version.kt
  settings.gradle.kts
  support/security/build.gradle.kts
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/error/JwtExpiredException.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/error/JwtVerificationException.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/util/JwtTokenProvider.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/vo/JwtClaims.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/vo/JwtClaimsDsl.kt
  support/security/src/test/kotlin/com/studentcenter/weave/support/security/jwt/util/JwtTokenProviderTest.kt
Labels: feat

#22 [WEAV-70] 소셜 로그인 API, 회원가입 필요 응답 상태코드 401 명세
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/AuthRestController.kt
Labels: feat

#24 [WEAV-72] ✨ 예외처리 핸들러 구현
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/ApiExceptionType.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/CustomExceptionHandler.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/ErrorResponse.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/UnknownExceptionHandler.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Version.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/exception/CustomException.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/exception/CustomExceptionType.kt
  support/common/src/main/kotlin/com/studentcenter/weave/support/common/exception/SystemExceptionType.kt
  support/security/build.gradle.kts
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/error/JwtExpiredException.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/error/JwtVerificationException.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/exception/JwtExceptionType.kt
  support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/util/JwtTokenProvider.kt
  support/security/src/test/kotlin/com/studentcenter/weave/support/security/jwt/util/JwtTokenProviderTest.kt
Labels: feat

#27 [WEAV-108] 토큰서비스 테스트 구현
  application/src/main/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/OpenIdTokenResolveStrategy.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/domain/impl/UserAuthInfoDomainServiceImplTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImplTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/KakaoOpenIdTokenResolveStrategyTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/common/properties/JwtTokenPropertiesFixtureFactory.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/common/properties/OpenIdPropertiesFixtureFactory.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserAuthInfoRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/OpenIdTokenResolveStrategyStub.kt
Labels: test

#29 [WEAV-62] 커버리지 측정문제 해결
  .github/workflows/develop_server_deployer.yaml
  .github/workflows/develop_server_integrator.yaml
  .github/workflows/pr_validator.yml
  .github/workflows/unit_test_runner.yaml
  build.gradle.kts
  settings.gradle.kts
  support/jacoco/build.gradle.kts
  support/security/src/test/kotlin/com/studentcenter/weave/support/security/jwt/util/JwtTokenProviderTest.kt
Labels: fix

#30 [WEAV-113] Add domain University and Major
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/UnivApi.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/UnivRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RegisterUserRequest.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/UniversitiesResponse.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/entity/Major.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/entity/University.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/entity/User.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/Major.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/MajorName.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/University.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/vo/UniversityName.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/entity/MajorTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/entity/UniversityTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/entity/UserAuthInfoTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/entity/UserTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/vo/MajorNameTest.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/vo/UniversityNameTest.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/entity/UserFixtureFactory.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/MajorJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/UniversityJpaEntity.kt
Labels: feat, test

#34 [WEAV-121] UserJpaEntity 구현
  application/src/main/kotlin/com/studentcenter/weave/application/port/inbound/UserRegisterUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserRepository.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/UserRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RegisterUserRequest.kt
  domain/src/main/kotlin/com/studentcenter/weave/domain/entity/User.kt
  domain/src/test/kotlin/com/studentcenter/weave/domain/entity/UserTest.kt
  domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/entity/UserFixtureFactory.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/adapter/UserJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/UserAuthInfoJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/UserJpaEntity.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/repository/UserJpaRepository.kt
  infrastructure/persistence/src/main/resources/application-persistence.yaml
  infrastructure/persistence/src/main/resources/db/migration/V3__create_user.sql
Labels: feat

#35 [WEAV-118] discord noti workflow 문법 오류 수정
  .github/workflows/develop_server_deployer.yaml
Labels: fix

#36 [WEAV-119] 회원가입 유스케이스 구현
  application/build.gradle.kts
  application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserAuthInfoRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/application/UserRegisterApplicationService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/domain/UserAuthInfoDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/domain/UserDomainService.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/domain/impl/UserAuthInfoDomainServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/domain/impl/UserDomainServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserRegisterApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/domain/impl/UserDomainServiceImplTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserAuthInfoRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserRepositorySpy.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/domain/UserDomainServiceStub.kt
  buildSrc/src/main/kotlin/Version.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/adapter/UserAuthInfoJpaAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/adapter/UserJpaAdapter.kt
Labels: feat

#37 [WEAV-119] 회원 유스케이스 테스트 리펙터링
  application/src/main/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImpl.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/OpenIdTokenResolveStrategyFactory.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/OpenIdTokenResolveStrategyFactoryImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserRegisterApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserSocialLoginApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/domain/impl/UserAuthInfoDomainServiceImplTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImplTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/domain/UserDomainServiceStub.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/util/UserTokenServiceStub.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/OpenIdTokenResolveStrategyFactoryStub.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/OpenIdTokenResolveStrategyStub.kt
Labels: refactor

#39 [WEAV-76] refresh token 발급시 redis 저장 연동
  application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserRefreshTokenRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImpl.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserRegisterApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserSocialLoginApplicationServiceTest.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImplTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserRefreshTokenRepositorySpy.kt
  bootstrap/http/build.gradle.kts
  bootstrap/http/compose-dev.yaml
  bootstrap/http/compose-local.yaml
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/UserRestController.kt
  infrastructure/redis/build.gradle.kts
  infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/adapter/UserRefreshTokenRedisAdapter.kt
  infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/common/config/RedisConfig.kt
  infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/entity/UserRefreshTokenRedisHash.kt
  infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/repository/UserRefreshTokenRedisRepository.kt
  infrastructure/redis/src/main/resources/application-redis.yaml
  settings.gradle.kts
Labels: feat

#40 [WEAV-125] 토큰 갱신 API 구현
  application/src/main/kotlin/com/studentcenter/weave/application/common/exception/AuthExceptionType.kt
  application/src/main/kotlin/com/studentcenter/weave/application/port/inbound/UserRefreshTokenUseCase.kt
  application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserRefreshTokenRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/service/application/UserRefreshTokenApplicationService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserRefreshTokenApplicationServiceTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserRefreshTokenRepositorySpy.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/AuthRestController.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RefreshLoginTokenResponse.kt
  infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/adapter/UserRefreshTokenRedisAdapter.kt
Labels: feat
