Repository Student-Center/weave-server, pull requests merged in 2024-05, with the labels that each got.

#260 [WEAV-000] 리프레쉬 토큰 만료 예외 변경 및 토큰 조회 메서드 리팩토링
  application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRefreshTokenRepository.kt
  application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/RefreshTokenService.kt
  application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/LogoutTest.kt
  application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRefreshTokenRepositorySpy.kt
  infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/user/adapter/UserRefreshTokenRedisAdapter.kt
Labels: refactor

#257 [WEAV-315] Sentry 라이브러리 연동
  bootstrap/http/build.gradle.kts
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/UnknownExceptionHandler.kt
  bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/WebSocketExceptionHandler.kt
  bootstrap/http/src/main/resources/application.yaml
  gradle/libs.versions.toml
Labels: config

#266 [WEAV-000] CD 워크플로우 수정 Revert
  .github/workflows/develop_server_deployer.yaml
Labels: fix
